[package]
name = "simple-db-rust"
version = "0.1.0"
authors = ["XiaochenCui <jcnlcxc.new@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
log = "0.4.8"
env_logger = "0.7.1"
bit-vec = "0.6.2"
lazy_static = "1.4.0"
